version: '3'
services:
  web:
    build:
      # Where we want all files and folders to be pulled from
      context: .
      # Location of dockerfile for the web service
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # Do not try to map a folder to these files
    volumes:
      - /app/node_modules
      - .:/app
  
  tests:
    build:
      # Where we want all files and folders to be pulled from
      context: .
      # Location of dockerfile for the web service
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
